controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_admin:
    path: /admin
    controller: 'App\Controller\Admin\IndexController::index'

app_client:
    path: /client
    controller: 'App\Controller\Client\IndexController::index'